FROM progrium/busybox:latest

RUN \
    opkg-install curl ca-certificates make coreutils-timeout && \
    sh -c "`curl -L https://raw.github.com/rylnd/shpec/master/install.sh`"

VOLUME "/tmp/wtfc"
WORKDIR "/tmp/wtfc"

CMD sh -c shpec